 # Etapa de construcción
 FROM maven:3.8-eclipse-temurin-21 AS builder
 WORKDIR /app
 COPY pom.xml .
 RUN mvn dependency:go-offline

 COPY src ./src
 RUN mvn package -Dmaven.test.skip=true

 # Etapa de ejecución
 FROM eclipse-temurin:21-jre
 WORKDIR /app
 COPY --from=builder /app/target/ms_clients-0.0.1-SNAPSHOT.jar app.jar
 ENTRYPOINT ["java", "-jar", "app.jar"]
